- name: Check that we declare the right hostname
  fail:
    msg: "Wrong hostname"
  when: "not (hostname | regex_search(zone + '$'))"

- name: Create builder instance
  ec2_instance:
    name: "{{ hostname }}"
    key_name: "ansible_bastion_keypair" 
#    vpc_subnet_id: "{{ vpc }}"
    instance_type: "{{ type }}"
    security_group: "{{ sg_group }}"
    network:
      assign_public_ip: true
    image_id: "{{ ami }}"
    region: "{{ aws_region }}"
    user_data: "{{ lookup('file', 'cloud-config.yml') }}"
    volumes:
    - device_name: /dev/sda1
      ebs:
        volume_size: 16
        delete_on_termination: true
  register: instance

- name: Add the DNS
  route53:
    state: present
    record: "{{ hostname }}"
    zone: "{{ zone }}"
    type: A
    ttl: 7200
    value: "{{ instance.instances[0].network_interfaces[0].private_ip_address }}"
    wait: yes
    overwrite: yes

- name: Prepare the new VM
  when: instance.changed
  block:
  - set_fact:
      public_ip: "{{ instance.instances[0].public_ip_address }}"
      location: aws
      #used by jenkins_builder role
      inventory_hostname: "{{ hostname }}"

  - wait_for:
      port: 22
      host: "{{ public_ip }}"

  - add_host:
      hostname: "{{ hostname }}"
      ansible_host: "{{ public_ip }}"
      groups:
      - int_aws_gluster_org
      - jenkins_builders_aws

  - command: "ssh -o 'PreferredAuthentications=publickey' -o 'StrictHostKeyChecking=no' {{ public_ip }} id"
    delegate_to: localhost
    ignore_errors: True

  - setup:
    delegate_to: "{{ hostname }}"

  - import_role:
      name: base
    delegate_to: "{{ hostname }}"

  - import_role:
      name: jenkins_builder
    delegate_to: "{{ hostname }}"

  - import_role:
      name: jenkins_builder_declaration
    delegate_to: jenkins_master
