- name: Add the jenkins repository
  yum_repository:
    name: jenkins
    description: Jenkins stable
    baseurl: https://pkg.jenkins.io/redhat-stable
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    gpgcheck: yes

- name: Install Jenkins
  package:
    name: jenkins
    state: installed

- name: Make sure Jenkins service is activated
  service:
    name: jenkins
    state: started
    enabled: True

- name: Setup the selinux boolean for proxying
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Download jenkins-cli.jar
  command: wget --no-check-certificate http://127.0.0.1/jnlpJars/jenkins-cli.jar -O /usr/local/bin/jenkins-cli.jar
  args:
    creates: /usr/local/bin/jenkins-cli.jar

- name: Add jenkins-cli wrapper
  copy:
    src: jenkins-cli
    dest: /usr/local/bin/jenkins-cli
    mode: 0755
    
