---
- name: Setup hosts file so that localhost is not used in /etc/hosts
  lineinfile:
    state: absent
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"

# we need the FQDN for various NFS test, due to usage of reverse
# DNS. Also, it need to be first in the file
- name: Setup hosts file so that external IP is in /etc/hosts
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ansible_default_ipv4['address'] }} {{ ansible_fqdn }}"
    insertbefore: BOF

- name: Remove the IPV6 entry
  lineinfile:
    state: absent
    dest: /etc/hosts
    regexp: "::1.*"

- stat:
    path: /etc/dhcp/dhclient.conf
  register: dhclient

- name: Setup DHCP client config so the nameservers are Google DNS servers
  lineinfile:
    state: present
    dest: /etc/dhcp/dhclient.conf
    line: "supersede domain-name-servers 8.8.8.8;"
  when: dhclient.stat.exists 

# since dhcp setting are applied only on next reboot 
- name: Make sure 8.8.8.8 is in resolve.conf
  lineinfile:
    state: present
    dest: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    regexp: "^nameserver.*"

- name: Disable DNS for DHCP on centos 8
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'
  block:
  - name: Add 8.8.8.8 to NetworkManager on C8
    nmcli:
      conn_name: eth0
      type: ethernet
      dns4:
      - 8.8.8.8
      state: present

  - name: Add 172.31.0.2 to NetworkManager on C8
    nmcli:
      conn_name: eth0
      type: ethernet
      dns4:
      - 172.31.0.2
      state: absent

  - name: Disable dhcp for C8
    shell: "nmcli con modify 'System eth0' ipv4.ignore-auto-dns true"

  - name: Really add 8.8.8.8 for C8
    shell: "nmcli con modify 'System eth0' ipv4.dns 8.8.8.8"

- name: Make sure that search do not come to interfer
  copy:
    dest: /etc/dhcp/dhclient.d/comment_search.sh
    src: comment_search.sh
    mode: 0755
