---
- name: Setup hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Setup hosts file so that IP is in /etc/hosts
  lineinfile:
    state: absent
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"

- name: Setup hosts file so that IP is in /etc/hosts
  lineinfile:
    state: absent
    dest: /etc/hosts
    line: "127.0.0.1 {{ inventory_hostname }}"
    insertbefore: BOF


- name: Setup hosts file so that IP is in /etc/hosts
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ansible_default_ipv4['address'] }} {{ ansible_hostname }}"
    insertbefore: BOF

- name: Setup hosts file so that IP is in /etc/hosts
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ansible_default_ipv4['address'] }} {{ inventory_hostname }}"
    insertbefore: BOF

- name: Remove the IPV6 entry
  lineinfile:
    state: absent
    dest: /etc/hosts
    regexp: "::1.*"

- stat:
    path: /etc/dhcp/dhclient.conf
  register: dhclient

- name: Setup DHCP client config so the nameservers are Google DNS servers
  lineinfile:
    state: present
    dest: /etc/dhcp/dhclient.conf
    line: "supersede domain-name-servers 8.8.8.8;"
  when: dhclient.stat.exists 

- name: Make sure that search do not come to interfer
  copy:
    dest: /etc/dhcp/dhclient.d/comment_search.sh
    src: comment_search.sh
    mode: 0755
