---
- name: Create private key for {{ domain }}
  openssl_privatekey:
    path: "{{ privatekey_path }}"

- name: Create signing request for {{ domain }}
  openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ privatekey_path }}"
    commonName: "{{ domain }}"

- name: Check certificate validity for {{ domain }}
  openssl_certificate:
    path: "{{ certificate_path }}"
    privatekey_path: "{{ privatekey_path }}"
    valid_in: "{{ 60 * 60 * 24 * 10 }}"
    provider: assertonly
  ignore_errors: True
  register: validity_check

- name: Create or renew certificate for {{ domain }}
  openssl_certificate:
    path: "{{ certificate_path }}"
    privatekey_path: "{{ privatekey_path }}"
    csr_path: "{{ csr_path }}"
    provider: acme
    acme_challenge_path: "{{ acme_webroot }}"
    acme_accountkey_path: "{{ acme_key }}"
    force: "{{ validity_check.failed }}"
  notify: Reload certificates everywhere
