---
dependencies:
- role: aws_builder
  # fbsd 12, from https://www.freebsd.org/releases/12.1R/announce.html
  ami: "ami-0a44f10b2c6deb365"
  user_data: "{{ lookup('template', 'configinit') }}" 
  labels:
  - freebsd12
  - freebsd
