---
- iam_user:
    name: "{{ item }}"
    state: present
  loop:
  - softserve
  - misc
  - deepshikha
  - sahina

- iam_group:
    name: Developers
    state: present
    users:
    - sahina

- iam_group:
    name: softserve
    state: present
    users:
    - softserve

- iam_group:
    name: gluster-janitors 
    state: present
    users:
    - misc
    - deepshikha
