---
- set_fact:
    directory: "/var/lib/jenkins/nodes/{{ hostname }}"

- name: Make sure the directory exist
  file:
    state: directory
    name: "{{ directory }}"

- name: Add config.xml
  template: 
    dest: "{{ directory }}/config.xml"
    src: config.xml
  notify: Reload jenkins configuration

- name: Get the ssh keys
  ssh_keyscan:
    name: "{{ hostname }}"
    ip: "{{ ip }}"
  register: r

- set_fact:
    key: "{{ r['keys'][ssh_key_type] }}"

- name: Add ssh-host-key.xml
  template:
    dest: "{{ directory }}/ssh-host-key.xml"
    src: ssh-host-key.xml
  notify: Reload jenkins configuration

