---
- name: Install nftables
  package:
    name: nftables
    state: present

- name: Deploy firewall rules
  template:
    dest: /etc/sysconfig/nftables.conf
    src: nftables.conf
  notify: Reload and verify nftables
# make sure firewalld is not running, since it
# make the postrouting stuff fail by default

- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: False
  ignore_errors: True

# do not start until everything is ready
- name: Start nftables service
  service:
    name: nftables
    state: started
    enabled: True

- name: Enable routing with sysctl
  sysctl:
    name: net.ipv4.ip_forward
    state: present
    value: '1'

#- name: Remove firewalld
#  package:
#    name: firewalld
#    state: absent
