- copy:
    src: zone_updater.py
    dest: /usr/local/bin/zone_updater.py
    mode: 0755

- cron:
    name: "update route53 zone"
    minute: "*/5"
    job: "python /usr/local/bin/zone_updater.py"
    user: ansible_admin
 
