---
- hosts: formicary.rht.gluster.org
  roles:
  - role: guest_firewall_rht
    vars:
      name: masa.rht.gluster.org
    network: 
      ip: 8.43.85.179/24
      gateway: 8.43.85.254

- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_firewall_rht
    vars:
      name: mune.rht.gluster.org
    network: 
      ip: 8.43.85.180/24
      gateway: 8.43.85.254


