---
- hosts: haplometrosis.rht.gluster.org
  vars:
    # default value for builders
    distribution: Centos
    version: 7
  roles:
  - role: guest_jenkins_builder_int_rht
    number: 0
  - role: guest_jenkins_builder_int_rht
    number: 1
  - role: guest_jenkins_builder_int_rht
    number: 2
  - role: guest_jenkins_builder_int_rht
    number: 4

  - role: guest_jenkins_builder_int_rht
    number: 49
    distribution: Fedora
    version: 32

 
- hosts: pleometrosis.rht.gluster.org
  vars: 
    # default value for builders
    distribution: Centos
    version: 7
  roles:
  - role: guest_jenkins_builder_int_rht
    number: 20
  - role: guest_jenkins_builder_int_rht
    number: 21
  - role: guest_jenkins_builder_int_rht
    number: 22
  - role: guest_jenkins_builder_int_rht
    number: 23
  - role: guest_jenkins_builder_int_rht
    number: 24
  - role: guest_jenkins_builder_int_rht
    number: 25
  - role: guest_jenkins_builder_int_rht
    number: 26
  - role: guest_jenkins_builder_int_rht
    number: 30
    version: 8
  - role: guest_jenkins_builder_int_rht
    number: 31
    version: 8
  - role: guest_jenkins_builder_int_rht
    number: 32
    version: 8
  - role: guest_jenkins_builder_int_rht
    number: 33
    version: 8
  - role: guest_jenkins_builder_int_rht
    number: 34
    version: 8
  - role: guest_jenkins_builder_int_rht
    number: 35
    version: 8
  - role: guest_jenkins_builder_int_rht
    number: 36
    version: 8
  - role: guest_jenkins_builder_int_rht
    number: 37
    version: 8
  - role: guest_jenkins_builder_int_rht
    number: 38
    version: 8
  - role: guest_jenkins_builder_int_rht
    number: 39
    version: 8

  - role: guest_jenkins_builder_int_rht
    number: 40
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 41
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 42
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 43
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 44
    distribution: Fedora
    version: 30
  - role: rht_builder_deb10
    lan_ip: 91
    hostname: builder-deb10-1

- hosts: pleometrosis.rht.gluster.org
  roles:
  - role: rht_builder_f32
    lan_ip: 92
    hostname: builder-f32-1

- hosts: pleometrosis.rht.gluster.org
  roles:
  - role: rht_builder_f32
    lan_ip: 93
    hostname: builder-f32-2


- hosts: jenkins_builders_rht
  tasks:
  - name: Resize the disk of the builders
    lvol:
      vg: "vg_root_{{ ansible_fqdn }}"
      lv: root
      size: 18G
    when: ansible_system == 'Linux'
  - name: Make sure the filesystem is resized
    filesystem:
      fstype: ext4
      dev: "/dev/mapper/vg_root_{{ ansible_fqdn }}-root"
      resizefs: True
    when: ansible_system == 'Linux'

# Fedora
- hosts: builder4[0-9].int.rht.gluster.org
  roles:
  - role: swap_file
    size: 2G
    path: /var/swap
